version: "3.8"

services:

  #  Another service.

  xythrion:
    container_name: xythrion
    init: true
    restart: always

    depends_on:
      - mysql

    env_file:
      - ./.env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./logs:/xythrion/logs:rw
      - .:/xythrion:ro

    ports:
      - "5005:5000"
