version: "3.8"

services:

  postgres:
    image: postgres:latest

    env_file:
      - ./.env

    expose:
      - 5432

    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/

  xythrion:
    container_name: xythrion
    init: true
    restart: always

    depends_on:
      - postgres

    env_file:
      - ./.env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./logs:/xythrion/logs
      - .:/xythrion:rw

    ports:
      - "5005:5000"